language: java
jdk:
  - openjdk8

# Travis CI를 어느 브랜치가 푸시될 때 수행할지 지정한다.
branches:
  only:
    - master

# 그레이들을 통해 의존성을 받게 되면 이를 해당 디렉토리에 캐시하여,
# 같은 의존성은 다음 배포 때부터 다시 받지 않도록 설정한다.
cache:
  # Travis CI 서버의 Home
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - chmod +x gradlew

# master 브랜치에 푸시되었을 때 수행하는 명령어이다.
# 프로젝트 내부에 둔 gradlew을 통해 clean & build를 수행한다.
script: "./gradlew clean build"

# Travis CI 실행 완료 시 자동으로 알람이 가도록 설정한다.
notifications:
  email:
    recipients:
      - hjclub123@gmail.com